# Generated by Django 5.0 on 2024-04-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderCart',
            new_name='OrderItems',
        ),
    ]
